# Generated by Django 5.1.2 on 2024-10-13 14:45

import cloudinary.models
import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[projects.models.validate_image], verbose_name='images'),
        ),
    ]
